---
title: "Manual QuAPPro"
subtitle: "An R/shiny web application for Quantification and Alignment of Polysome Profiles"
author: "Chiara Schiller and Johanna Schott"
date: "30.04.2024"
output: html_document
runtime: shiny
---


# Table of contents
1. [Introduction](#introduction)
2. [File Import](#file-import)  
3. [Selected Profile](#profile)  
4. [UV Profile](#polysome-profile)
5. [Fluorescence Profile](#fluorescence-profile)
6. [Quantification](#quantification)
7. [Aligned Profiles](#aligned-profiles)
8. [Alignment](#alignment)
9. [Colors and Lines](#colors-and-lines)
10. [Normalization](#normalization)
11. [File Export](#file-export)

## 1. Introduction <a name="introduction"></a>
In order to facilitate and improve the analysis and comparison of polysome profiles, we created a tool that allows interactive alignment of polysome profiles and quantification of subsections of individual profiles using the Shiny Web App format. QuAPPro also allows visualization and quantification of associated fluorescence signals.

For optimal display of the app, please reduce the zoom factor of your browser until you can see the three logos in the corners of our layout simultaneously!

## 2.	File Import <a name="file-import"></a>
QuAPPro accepts different text file formats as input via the file browser. Multiple files can be imported at once. As default, QuAPPro expects .pks files as generated by the Teledyne ISCO PeakTrak software. In these files, columns are separated by a space, a comma is used as decimal separator (German settings) and the UV absorbance is provided in the third column. The dropdown menu “Profile type” allows two more options as file types: “TRIAX (UV)” refers to .csv files generated with the BioComp FlowCell software, where the first 47 lines need to be skipped, columns are separated by a comma, a point is used as decimal separator, and UV absorbance is provided in the fourth column. “TRIAX (Fl)” refers to BioComp FlowCell files including a fluorescence signal, where the first 51 lines need to be skipped, UV absorbance is provided in the fifth and the fluorescence signal in the third column. With “Custom”, the settings are adjusted to a tab-separated file with a decimal point and UV absorbance in the second column. All these parameters can be adjusted via the respective drop-down menus! The imported profiles can be selected from the “Select a profile” dropdown menu and are displayed in the “Selected Profile” area. Alternatively, you can also import a previous analysis as .RData file via the file browser (see section [File Export](#file-export)).

## 3.	Selected Profile <a name="selected-profile"></a>
The line plots displayed in the “Selected Profile” area show UV absorbance values on the y-axis and the row number of the corresponding data point on the x-axis. Under the profile plot, you find the options “Automatic min/max recognition” and “Automatic inflection recognition”. They refer to the interaction of the user with the plot when the x-anchor for alignment (see section [Polysome Profile](#polysome-profile)) or start and end of an area is defined (see section [Quantification](#quantification)). When these options are selected and you click into the plot, the closest local maximum/minimum or the closest inflection point is selected. The plot that you currently see in the plotting area can be downloaded as PDF via the ”Download Plot” button.

## 4.	UV Profile <a name="polysome-profile"></a>
The axis limits of the polysome profile plot displayed in the “Selected Profile” area can be adjusted with the respective input fields (“Set y min” etc.). We offer the possibility to smooth UV absorbance profiles with the “Smooth” function. As long as the input field contains 0 or is empty, no smoothing is performed. The degree of smoothing can be regulated with the number entered into the field. For aligning your selected profile to other polysome profiles, you can interactively choose a baseline and a so-called X-anchor. The X-anchor is the position used for alignment along the x-axis. You can enter the interactive mode with the buttons “Baseline” and “X-anchor”, respectively, and then click into the plot until you are satisfied with the selected line. For selecting an X-anchor, the closest local minimum or maximum is automatically detected if the option “Automatic min/max recognition” under the plot is selected. This can be convenient when you want to align your profiles e.g. along the monosome peak or the valley between monosomes and disomes. Alternatively, you can select the closest inflection point with “Automatic inflection recognition” or simply the data point closest to your click when none of these options is selected. 

## 5.	Fluorescence Profile <a name="fluorescence-profile"></a>
If your data contains a fluorescence signal (as it is the case for the TRIAX system from BioComp), you can display it by selecting “Show”. The axis limits of the fluorescence profile plot can be adjusted with the respective input fields (“Set y min” etc.). We offer the possibility to smooth fluorescence profiles with the “Smooth” function. As long as the input field contains 0 or is empty, no smoothing is performed. The degree of smoothing can be regulated with the number entered into the field. For aligning your selected fluorescence profile to other fluorescence profiles, you have to choose a baseline. You can enter the interactive mode with the button “Baseline” and then click into the plot. The X-anchor is selected from the corresponding polysome profile (see section [Polysome Profile](#polysome-profile)). 

## 6.	Quantification <a name="quantification"></a>
For quantifying areas under the polysome profile, you have to define the start and the end of the area to quantify. Enter the interactive mode with the “Start” or “End” buttons and click into the plot. The closest local minimum or maximum is automatically detected if the option “Automatic min/max recognition” under the plot is selected. Alternatively, you can select the closest inflection point with “Automatic inflection recognition” or simply the data point closest to your click when none of these options is selected. Selecting an inflection point may be useful when two peaks overlap strongly and are not separated by a defined local minimum. With the button “Quantify”, the sum of values between the selected start and end point is calculated and appears green once successfully quantified. The name of the quantified area can be selected from the dropdown menu “Select area”, where we offer a few common choices. The quantified and named area is added to the table in the tab “Quantification Summary”, which can be downloaded as .csv file. Further names can be entered into the text field and added to the selection. If a fluorescence profile is displayed, the respective area under the fluorescence signal is also quantified and added to the table in the “Quantification Summary” (columns ending in _fluo).

## 7.	Aligned Profiles <a name="aligned-profiles"></a>
As soon as a polysome profile has a baseline and an X-anchor (see section [Polysome profile](#polysome-profile)), it is displayed in the plotting area “Aligned Profiles”. The plot can be downloaded as PDF via the ”Download Plot” button. Colors and legend names are set automatically but can be modified in the section “Alignment”.

## 8.	Alignment <a name="alignment"></a>
All profiles that are available for alignment (because baseline and X-anchor have been set) can be selected from the dropdown menu “Available profiles”. The order of profiles in the alignment plot can be changed with the arrows on the right side of the dropdown menu. When the “Display” option is unticked, the selected profile is hidden from the alignment plot. If you want to change the name of the selected profile in the legend, enter the new name in the input field “Name in legend” and press “Rename”. The values shown in the alignment plot are available for download as .csv file.

## 9.	Colors and Lines <a name="colors-and-lines"></a>
The appearance of the selected profile can be further modified regarding their color, line type and line width. By default, the palette “Dark 3” of the R package colorspace is used. In addition, the rainbow palette and a color-blind friendly palette from the R package colorBlindness are available. When the color palette is changed, colors that were set individually for a selected profile will be over-written.

## 10.	Normalization <a name="normalization"></a>
Sometimes, the overall amount of material on your gradients might differ, or the length of the profile might vary due to changes in elution speed between experiments. When an area with the name “Total” was quantified for all profiles in the alignment (see section [Quantification](#quantification)), it is possible to normalize for the total area under the polysome profile, or for the length of the total area. You can select the respective normalization procedure with “Normalize area” or “Normalize length”. With these options, it is even possible to align profiles from devices with different temporal resolution and sensitivity to each other.

## 11.	File Export <a name="file-export"></a>
To resume an ongoing analysis, it is possible to export the entire analysis as .RData file with “Export Analysis” and re-import it via the file browser (see section [File Import](#file-import)).