---
title: "Manual QuAPPro"
subtitle: "An R/shiny web application for Quantification and Alignment of Polysome Profiles"
author: "Chiara Schiller and Johanna Schott"
date: "´19.12.2024"
output: html_document
runtime: shiny
---




# Table of contents
1. [Introduction](#introduction)
2. [Guided tutorials in the app](#tutorials)
3. [Tab I: Alignment/Areas](#alignment-areas)     
  a. [File Import](#file-import)      
  b. [Selected Profile](#profile)     
  c. [UV Profile](#polysome-profile)      
  d. [Fluorescence Profile](#fluorescence-profile)      
  e. [Quantification](#quantification)      
  f. [Aligned Profiles](#aligned-profiles)      
  g. [Alignment](#alignment)      
  h. [Colors and Lines](#colors-and-lines)      
  i. [Normalization](#normalization)      
  j. [File Export](#file-export)      
4. [Tab II: Deconvolution](#de-convolution)
5. [Tab III: Alignment Table](#alignmenttable)
6. [Tab IV: Quantification Summary](#quantification-summary)
7. [Tab V: Bar Plots](#barplots)    
  a. [Feature Selection](#feature-selection)       
  b. [Condition Assignment](#conditions)       


## 1. Introduction <a name="introduction"></a>
In order to standardize and facilitate the analysis of polysome profiles, we created a tool that allows interactive alignment of polysome profiles and quantification of subsections of individual profiles using the R Shiny Web App format. QuAPPro also allows visualization and quantification of associated fluorescence signals.


For optimal display of the app, please reduce the zoom factor of your browser until you can see the three logos in the corners of our layout simultaneously! 

## 2. Guided tutorials in the app <a name="tutorials"></a>
In the right upper corner of the Alignment/Areas, Deconvolution and Bar Plot tabs are buttons to load example data and to start guided tours through the functionalities of the respective tab. After clicking the "Guided Tour” button, you will be walked through the most important steps of the interactive analysis. After clicking through all explanations or clicking cancel at any point of the tour, you can explore the interactive functionalities with the loaded example data yourself. Reload the browser to erase the exemplary profiles and to start analyzing your own data!

## 3. Tab I: Alignment/Areas <a name="alignment-areas"></a>

### a.	File Import <a name="file-import"></a>
QuAPPro accepts different text file formats as input via the file browser. Examples for all file types can be downloaded from our [GitHub repository](https://github.com/johannaschott/QuAPPro/tree/main/input_examples). Multiple files of the same format can be imported at once. As a default, QuAPPro expects .pks files as generated by the Teledyne ISCO PeakTrak software. In these files, columns are separated by a space, a comma is used as decimal separator (German settings) and the UV absorbance is provided in the third column. All parameters can be adjusted via the respective drop-down menus, to adjust the import settings. For convenience, the dropdown menu “Profile type” allows four more options with pre-defined settings: “TRIAX (UV)” refers to .csv files generated with the BioComp FlowCell software, where the first 47 lines need to be skipped, columns are separated by a comma, a point is used as decimal separator, and UV absorbance is provided in the fourth column. “TRIAX (Fl)” refers to BioComp FlowCell files including a fluorescence signal, where the first 51 lines need to be skipped, UV absorbance is provided in the fifth and the fluorescence signal in the third column. "PrimeView" profiles contain a space as a column separator, a comma as decimal separator, and the first 2 lines are skipped. With “Custom”, the settings are adjusted to a tab-separated file with a decimal point and UV absorbance in the second column. The imported profiles can be selected from the “Select a profile” dropdown menu and are displayed in the “Selected Profile” area. Alternatively, you can also import a previous analysis as .RData file via the file browser (see section [File Export](#file-export)).


### b.	Selected Profile <a name="selected-profile"></a>
The line plots displayed in the “Selected Profile” area show UV absorbance values on the y-axis and the row number of the corresponding data point on the x-axis. Under the profile plot, you find the options “Automatic min/max recognition” and “Automatic inflection recognition”. They refer to the interaction of the user with the plot when the x-anchor for alignment (see section [Polysome Profile](#polysome-profile)) or start and end of an area is defined (see section [Quantification](#quantification)). When these options are selected and you click into the plot, the closest local maximum/minimum or the closest inflection point is selected. The plot that you currently see in the plotting area can be downloaded as PDF via the ”Download Plot” button.


### c.	UV Profile <a name="polysome-profile"></a>
The axis limits of the polysome profile plot displayed in the “Selected Profile” area can be adjusted with the respective input fields (“Set y min” etc.). We offer the possibility to smooth UV absorbance profiles with the “Smooth” function. As long as the input field contains 0 or is empty, no smoothing is performed. The degree of smoothing can be regulated with the number entered into the field. For aligning your selected profile to other polysome profiles, you can interactively choose a baseline and a so-called X-anchor. The X-anchor is the position used for alignment along the x-axis. You can enter the interactive mode with the buttons “Baseline” and “X-anchor”, respectively, and then click into the plot until you are satisfied with the selected line. For selecting an X-anchor, the closest local minimum or maximum is automatically detected if the option “Min/max detection” under the plot is selected. This can be convenient when you want to align your profiles e.g. along the monosome peak or the valley between monosomes and disomes. Alternatively, you can select the closest inflection point with “Inflection detection” or simply the data point closest to your click when none of these options is selected. 


### d.	Fluorescence Profile <a name="fluorescence-profile"></a>
If your data contains a fluorescence signal (as it is the case for the TRIAX system from BioComp), you can display it by selecting “Show”. The axis limits of the fluorescence profile plot can be adjusted with the respective input fields (“Set y min” etc.). We offer the possibility to smooth fluorescence profiles with the “Smooth” function. As long as the input field contains 0 or is empty, no smoothing is performed. The degree of smoothing can be regulated with the number entered into the field. For aligning your selected fluorescence profile to other fluorescence profiles, you have to choose a baseline. You can enter the interactive mode with the button “Baseline” and then click into the plot. The X-anchor is selected from the corresponding polysome profile (see section [Polysome Profile](#polysome-profile)). 


### e.	Quantification <a name="quantification"></a>
For quantifying areas under the polysome profile, you have to define the start and the end of the area to quantify. Enter the interactive mode with the “Start” or “End” buttons and click into the plot. The closest local minimum or maximum is automatically detected if the option “Min/max detection” under the plot is selected. Alternatively, you can select the closest inflection point with “Inflection detection” or simply the data point closest to your click when none of these options is selected. Selecting an inflection point may be useful when two peaks overlap strongly and are not separated by a defined local minimum. With the button “Quantify”, the sum of values between the selected start and end point is calculated and appears green once successfully quantified. The name of the quantified area can be selected from the dropdown menu “Select area”, where we offer a few common choices. The quantified and named area is added to the table in the tab “Quantification Summary”, which can be downloaded as a .csv file. Further names can be entered into the text field and added to the selection. If a fluorescence profile is displayed, the respective area under the fluorescence signal is also quantified and added to the table in the “Quantification Summary” (columns ending in _fluo_area).


### f.	Aligned Profiles <a name="aligned-profiles"></a>
As soon as a polysome profile has a baseline and an X-anchor (see section [Polysome profile](#polysome-profile)), it is displayed in the plotting area “Aligned Profiles”. The plot can be downloaded as PDF via the ”Download Plot” button. Colors and legend names are set automatically but can be modified in the section “Alignment”.


### g.	Alignment <a name="alignment"></a>
All profiles that are available for alignment (because baseline and X-anchor have been set) can be selected from the dropdown menu “Available profiles”. The order of profiles in the alignment plot can be changed with the arrows on the right side of the dropdown menu. When the “Display” option is unticked, the selected profile is hidden from the alignment plot. If you want to change the name of the selected profile in the legend, enter the new name in the input field “Name in legend” and press “Rename”. The values shown in the alignment plot are available for download as .csv file.


### h.	Colors and Lines <a name="colors-and-lines"></a>
The appearance of the selected profile can be further modified regarding their color, line type and line width. By default, the palette “Dark 3” of the R package colorspace is used. In addition, the rainbow palette and a color-blind friendly palette from the R package colorBlindness are available. When the color palette is changed, colors that were set individually for a selected profile will be overwritten.


### i.	Normalization <a name="normalization"></a>
Sometimes, the overall amount of material on your gradients might differ, or the length of the profile might vary due to changes in elution speed between experiments. When an area with the name “Total” was quantified for all profiles in the alignment (see section [Quantification](#quantification)), it is possible to normalize for the total area under the polysome profile, or for the length of the total area. You can select the respective normalization procedure with “Normalize area” or “Normalize length”. With these options, it is even possible to align profiles from devices with different temporal resolution and sensitivity to each other.


### j.	File Export <a name="file-export"></a>
To resume an ongoing analysis, it is possible to export the entire analysis as .RData file with “Export Analysis” and re-import it via the file browser (see section [File Import](#file-import)).


## 4. Tab II: Deconvolution <a name ="de-convolution"></a>
For quantifying individual peaks that partially overlap with neighboring peaks, a deconvolution of the region around the peak of interest can be performed to compensate for the overlap. 
As soon as a baseline was selected for a UV profile in the main tab, the profile is displayed in the "Deconvolution" tab (lower panel), together with its second derivative (upper panel). All negative local minima of the second derivative are marked with grey dashed lines as putative positions of peaks underlying the profile. The second derivative can be modified by smoothing. As long as the input field "Smooth (2nd deriv.)" contains 0 or is empty, no smoothing is performed. The degree of smoothing can be regulated with the number entered into the field, which is then used as a spar parameter (controls smoothing) for the R function smooth.spline(). In addition, the resolution for identifying local minima can be adjusted with the field "Resolution". By default, at least five consecutively decreasing followed by five consecutively increasing values are required to define a local minimum (which can be separated by a plateau of equal values). The region of the UV profile that should be used for modelling individual peaks is defined interactively by clicking into the UV abs. plot (lower panel), after activating the "Start" or "End" button, respectively. The closest local minimum or maximum is automatically detected if the option “Min/max detection” is selected. In addition, you can select the closest inflection point with “Inflection detection” or simply the data point closest to your click when none of these options is selected. After selecting both start and end of the region, deconvolution is activated with "Go". Non-linear regression is used to estimate the position, standard deviation and height of Gaussian distributions as a model for individual peaks. The positions are restricted to the location of the identified second derivative minima with a tolerance of 1% of the entire profile length to the left and to the right. The estimated parameters are provided as a table and can be downloaded as a .csv file. When deconvolution was successful, you can select individual peaks by clicking into the plot and add their value to the table in the "Quantification Summary" tab with "Quantify". The name of the quantified peak can be selected from the dropdown menu “Select peak”, where we offer a few common choices. Further names can be entered into the text field and added to the selection.
Deconvolution failed: The overlap between the peaks in a polysome profile is often very strong, especially in the polysomal part. In addition, small hidden peaks can distort the shape of larger peaks, so that they cannot be modeled well with a Gaussian distribution. This can be the case due to an additional small ribosomal subunit that is not resolved as a separate peak under most conditions (halfmers). At the beginning and the end of the profile, peaks are also not resolved in a symmetric way. For all these reasons, deconvolution of polysome profiles is often only possible in a very restricted range of a profile, where peaks do not overlap too strongly and show a Gaussian shape. For polysome profiles from mammalian cell lines, this is typically the case from the 40S to the 80S peak. Further deconvolution into the polysomes is only possible when the peaks are not too asymmetric. If the model does not converge, the message "Deconvolution failed" will be displayed. 

## 5. Tab III: Alignment table <a name ="alignmenttable"></a>
All aligned profile values can be downloaded here in one .csv table. The displayed values correspond to the current analysis status (normalized/not normalized) in the “Alignment/Areas” tab. When "Normalize length (x-values)" was ticked, NAs will have to be introduced.


## 6. Tab IV: Quantification summary <a name ="quantification-summary"></a>
All quantified areas per profile from the “Alignment/Areas” or the "Deconvolution” tab analysis can be downloaded here as .csv file.


## 7. Tab V: Bar Plot <a name="barplots"></a>
Once areas or peaks were quantified, the values can be summarized, normalized and visualized in the Bar Plot tab. 

### a. Feature Selection  <a name="feature-selection"></a>
Please select the area or peak of interest from the "Select Values" dropdown menu. If you would like to normalize the selected value to another feature, select the respective area under "Normalization". For example, the proportion of polysomes relative to the total area is often measured as a proxy for global translation efficiency. In this case, "Polysomes_area" should be chosen as values, and "Total_area" as normalization.

### b. Condition Assignment  <a name="conditions"></a>
Assign conditions to the individual profiles in the columns Condition 1 and Condition 2 directly in the table, which you can also download here. Values with the same entry will be treated as a group, and the mean and standard deviation will be displayed as a bar plot. If there are entries in the column Condition 2, a grouped bar plot will be generated. The colours of the bars and data points can be modified separately. If there are entries in Condition 2, the colours selected for Condition 1 will be ignored. You can download the bar plot as PDF via the ”Download Plot” button.
